spring:
  datasource:
    url: jdbc:h2:mem:testdb
    #initialization-mode: always
    #schema: schema.sql
    #data: data.sql
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

#    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, logfile
  endpoint:
    health:
      show-details: always
  security:
    enabled: false

logging:
  file:
    path: ./library-application
  level:
    ROOT: INFO