INSERT INTO AUTHORS (NAME)
VALUES ('PUSHKIN');
INSERT INTO GENRES (NAME)
VALUES ('POEM');

INSERT INTO BOOKS (NAME, AUTHOR_ID, GENRE_ID)
SELECT 'EVGENII ONEGIN', A.ID, G.ID
FROM AUTHORS A, GENRES G
WHERE A.NAME = 'PUSHKIN'
AND G.NAME = 'POEM';

INSERT INTO AUTHORS (NAME)
VALUES ('MONTGOMERY');
INSERT INTO GENRES (NAME)
VALUES ('NOVEL');

INSERT INTO BOOKS (NAME, AUTHOR_ID, GENRE_ID)
SELECT 'ANNE OF GREEN GABLES', A.ID, G.ID
FROM AUTHORS A, GENRES G
WHERE A.NAME = 'MONTGOMERY'
AND G.NAME = 'NOVEL';

INSERT INTO USERS (USERNAME, PASSWORD)
VALUES ('USER', 'USER');
INSERT INTO USERS (USERNAME, PASSWORD)
VALUES ('ADMIN', 'ADMIN');

INSERT INTO ROLES (ROLE, USER_ID)
SELECT 'USER', U.ID
FROM USERS U
WHERE U.USERNAME = 'USER';

INSERT INTO ROLES (ROLE, USER_ID)
SELECT 'USER', U.ID
FROM USERS U
WHERE U.USERNAME = 'ADMIN';

INSERT INTO ROLES (ROLE, USER_ID)
SELECT 'ADMIN', U.ID
FROM USERS U
WHERE U.USERNAME = 'ADMIN';